apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elasticsearch-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: juan-pablo/kibana:latest
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch-master:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elasticsearch-cluster
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: NodePort