apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-mpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-mpi
  template:
    metadata:
      labels:
        app: engine-mpi
    spec:
      containers:
        - name: engine-mpi
          image: jogodavida-mpi:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6600
          resources:
            requests: # O que o Pod idealmente precisa para agendamento
              cpu: "1" # Pede 1 núcleo (ou 1000m)
              memory: "1Gi" # Exemplo: 1 GB de RAM
            limits: # O máximo que o Pod pode usar
              cpu: "2" # Limite de 2 núcleos (ou 2000m)
              memory: "2Gi" # Exemplo: Limite de 2 GB de RAM